### ISSUE TITLE
audio preview changes before and after upload.

### ISSUE THREAD

**Issue by yarix** [kartik-v/bootstrap-fileinput#306]
when i "browse" for audio file, the preview zone height is shrink to the size of the audio control (which is about ~80px.
this looks very nice.

when i click the upload button, and return the below initial-preview, the <div> that wraps the audio control, changes to 160px. ... which does not look good (the bug)
```javascript
{"initialPreview":["<audio controls=\"\">
<source src=\"/myFiles/1812d1d093d7\" type=\"audio/wav\" /><div class=\"file-preview-other\">
<i class=\"glyphicon glyphicon-file\"></i></div></audio>"],

"initialPreviewConfig":[{"caption":"sample.wav","url":"/del/1812d1d093d7"}]
}
````
NOTE: 
my local workaround was to comment out the height line in the .file-preview-frame class 
````css
.file-preview-frame {
    display: table;
    margin: 8px;
    /* height: 160px; */
    border: 1px solid #ddd;
    box-shadow: 1px 1px 5px 0px #a2958a;
    padding: 6px;
    float: left;
    text-align: center;
    vertical-align: middle;
}
````
