### ISSUE TITLE
Wrong Layout

### ISSUE THREAD

**Issue by gandarez** [kartik-v/bootstrap-fileinput#363]
Hi guys,
How can I solve this layout mistake?
```css
.btn-file {
    position: relative;
    overflow: hidden;
}
.btn-file input[type=file] {
    position: absolute;
    top: 0;
    right: 0;
    min-width: 100%;
    min-height: 100%;
    font-size: 100px;
    text-align: right;
    filter: alpha(opacity=0);
    opacity: 0;
    outline: none;
    background: white;
    cursor: inherit;
    display: block;
}
```
![image](https://cloud.githubusercontent.com/assets/782854/8855483/c1b2671c-313b-11e5-9b79-2f1bbe976a3e.png)
